# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  arm-build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0.203-jammy-arm64v8
      volumes:
        - /github/home/out:/github/home/out
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          dotnet publish src/ConsoleHost/Logship.Agent.ConsoleHost.csproj -c Release -r linux-arm64 -o /github/home/out --self-contained true

      - name: Package
        shell: pwsh
        run: |
          Get-ChildItem "/github/home/out/Logship.Agent.ConsoleHost.exe", "/github/home/out/Logship.Agent.ConsoleHost", "/github/home/out/appsettings.json" -ErrorAction SilentlyContinue |
            Compress-Archive -DestinationPath "LogshipAgent-linux-arm64.zip"

      - uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: |
            *.zip