name: Build & Release

on: push
  # push:
  #   tags:
  #     - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOTNET_VERSION: '8.0.203'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Build
        run: |
          dotnet publish src/ConsoleHost/Logship.Agent.ConsoleHost.csproj -c Release -o out --self-contained true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
            out/Logship.Agent.ConsoleHost
            out/Logship.Agent.ConsoleHost.exe
  
  container-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push OCI Image
        run: |
          podman build . --file Containerfile --tag ghcr.io/${{ github.repository }}:$GITHUB_REF_NAME
          podman tag ghcr.io/${{ github.repository }}:$GITHUB_REF_NAME ghcr.io/${{ github.repository }}:latest
          podman push ghcr.io/${{ github.repository }}:$GITHUB_REF_NAME
          podman push ghcr.io/${{ github.repository }}:latest
        
  bin-release:
    runs-on: ubuntu-latest
    name: Release ${{ github.ref_name }}
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: out/
      
      - name: Display structure of downloaded files
        run: |
          echo "${{ github.ref_name }}"
          ls -R out/
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: false
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: false
          title: "Agent Release ${{ github.ref_name }}"
          files: |
            out/Logship.Agent.ConsoleHost
            out/Logship.Agent.ConsoleHost.exe
    
